/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import controller.ListaDeEquipos;
import controller.ListaDeUsuarios;
import controller.ListaLaboratorios;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Laboratorio;
import model.Usuario;

/**
 *
 * @author derno
 */
public class CrearEquipos2 extends javax.swing.JPanel {
    
    private Usuario userActual;
    private ListaLaboratorios listalaboratorios;
    private ListaDeEquipos listaequipos;
    
    private String descripcion;
    private String marca;
    private String modelo;
    private String numeroSerial;
    private String numeroActivo;
    private String presentacion;
    private String voltaje;
    private String procesable;
    private String materialRequerido;
    private String añoDeCompra;
    
    public CrearEquipos2(Usuario user, ListaLaboratorios listaLab, ListaDeEquipos equipos, 
                         String descripcion, String marca, String modelo, String numeroSerial, 
                         String numeroActivo, String presentacion, String voltaje, 
                         String procesable, String materialRequerido, String añodecompra) {
        initComponents();
        this.userActual = user;
        this.listalaboratorios = listaLab;
        this.listaequipos = equipos;
        this.descripcion = descripcion;
        this.marca = marca;
        this.modelo = modelo;
        this.numeroSerial = numeroSerial;
        this.numeroActivo = numeroActivo;
        this.presentacion = presentacion;
        this.voltaje = voltaje;
        this.procesable = procesable;
        this.materialRequerido = materialRequerido;
        this.añoDeCompra = añoDeCompra;
        initLabDisponible();
        LabDisponible.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            LabDisponibleActionPerformed(evt);
        }
    });
    }
    
      private void MostrarJpanel(JPanel p){
        p.setSize(1180,780);   
        p.setLocation(0,0);
        BackgroundCrearEquipos2.removeAll();
        BackgroundCrearEquipos2.add(p,BorderLayout.CENTER);
        BackgroundCrearEquipos2.revalidate();
        BackgroundCrearEquipos2.repaint();
    }
    private void initLabDisponible() {
        ArrayList<Laboratorio> laboratorios = listalaboratorios.getListaLaboratorios();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        for (Laboratorio lab : laboratorios) {
            model.addElement(lab.getNombreLaboratorio());
        }

        LabDisponible.setModel(model);
    }

    private void LabDisponibleActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String nombreLaboratorioSeleccionado = (String) LabDisponible.getSelectedItem();
        String idLaboratorio = listalaboratorios.listarLaboratorioPorNombre(nombreLaboratorioSeleccionado);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EncendidoNoche = new javax.swing.ButtonGroup();
        BackgroundCrearEquipos2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLbl1 = new javax.swing.JLabel();
        AplicacionTXT = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        CrearEquiposFinal = new javax.swing.JButton();
        nameLbl3 = new javax.swing.JLabel();
        UltimoMantenimientoTXT = new javax.swing.JTextField();
        nameLbl6 = new javax.swing.JLabel();
        ProximaCalibracionTXT = new javax.swing.JTextField();
        nameLbl4 = new javax.swing.JLabel();
        ProvedorServicioTXT = new javax.swing.JTextField();
        nameLbl5 = new javax.swing.JLabel();
        ProximoMantenimientoTXT = new javax.swing.JTextField();
        nameLbl7 = new javax.swing.JLabel();
        UltimaCalibracionTXT = new javax.swing.JTextField();
        nameLbl9 = new javax.swing.JLabel();
        NombreProductoTXT = new javax.swing.JTextField();
        nameLbl10 = new javax.swing.JLabel();
        ObservacionesTXT = new javax.swing.JTextField();
        nameLbl8 = new javax.swing.JLabel();
        EncendidoNocheSi = new javax.swing.JRadioButton();
        EncendidoNocheNo = new javax.swing.JRadioButton();
        nameLbl12 = new javax.swing.JLabel();
        InventarioExistenteTXT = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        nameLbl11 = new javax.swing.JLabel();
        LabDisponible = new javax.swing.JComboBox<>();

        BackgroundCrearEquipos2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Crear Equipo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Por favor, ingrese los datos para poder crear el equipo: ");

        nameLbl1.setText("Ingrese la aplicacion:");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        CrearEquiposFinal.setBackground(new java.awt.Color(21, 101, 192));
        CrearEquiposFinal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearEquiposFinal.setForeground(new java.awt.Color(255, 255, 255));
        CrearEquiposFinal.setText("Siguiente");
        CrearEquiposFinal.setBorder(null);
        CrearEquiposFinal.setBorderPainted(false);
        CrearEquiposFinal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CrearEquiposFinal.setIconTextGap(13);
        CrearEquiposFinal.setInheritsPopupMenu(true);
        CrearEquiposFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEquiposFinalActionPerformed(evt);
            }
        });

        nameLbl3.setText("Ingrese el ultimo mantenimiento:");

        nameLbl6.setText("Ingrese la proxima calibracion:");

        nameLbl4.setText("Ingrese el provedor de servicio:");

        nameLbl5.setText("Ingrese el proximo mantenimiento:");

        nameLbl7.setText("Ingrese la ultima calibracion:");

        nameLbl9.setText("Nombre del producto:");

        nameLbl10.setText("Ingrese las observaciones: ");

        nameLbl8.setText("Encendido de noche:");

        EncendidoNoche.add(EncendidoNocheSi);
        EncendidoNocheSi.setText("Si");

        EncendidoNoche.add(EncendidoNocheNo);
        EncendidoNocheNo.setText("No");

        nameLbl12.setText("Inventario existente:");

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));

        nameLbl11.setText("Escoja el laboratorio a asignar:");

        LabDisponible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout BackgroundCrearEquipos2Layout = new javax.swing.GroupLayout(BackgroundCrearEquipos2);
        BackgroundCrearEquipos2.setLayout(BackgroundCrearEquipos2Layout);
        BackgroundCrearEquipos2Layout.setHorizontalGroup(
            BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addComponent(nameLbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(196, 196, 196))
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                        .addComponent(nameLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(51, 51, 51))
                                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                        .addComponent(nameLbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(29, 29, 29))
                                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                        .addComponent(nameLbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(42, 42, 42))
                                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(UltimoMantenimientoTXT)
                                            .addComponent(AplicacionTXT)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ProximoMantenimientoTXT)
                                            .addComponent(UltimaCalibracionTXT))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(ProvedorServicioTXT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addComponent(nameLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49))
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addComponent(ProximaCalibracionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ObservacionesTXT)
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(187, 187, 187))
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl8, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addGap(319, 319, 319))
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(EncendidoNocheSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(EncendidoNocheNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(333, 333, 333))
                            .addComponent(NombreProductoTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(243, 243, 243))
                            .addComponent(InventarioExistenteTXT)
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(CrearEquiposFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addComponent(nameLbl11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(157, 157, 157))
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addComponent(LabDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        BackgroundCrearEquipos2Layout.setVerticalGroup(
            BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addComponent(nameLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(AplicacionTXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(UltimoMantenimientoTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(ProximoMantenimientoTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(UltimaCalibracionTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(ProximaCalibracionTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(ProvedorServicioTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addGap(80, 80, 80))
            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(nameLbl8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncendidoNocheNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EncendidoNocheSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLbl9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreProductoTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLbl12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InventarioExistenteTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLbl10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ObservacionesTXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLbl11)
                .addGap(18, 18, 18)
                .addComponent(LabDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(CrearEquiposFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCrearEquipos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCrearEquipos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearEquiposFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEquiposFinalActionPerformed
        String aplicacion = AplicacionTXT.getText();
        String ultimoMantenimiento = UltimoMantenimientoTXT.getText();
        String proximoMantenimiento = ProximoMantenimientoTXT.getText();
        String ultimaCalibracion = UltimaCalibracionTXT.getText();
        String proximaCalibracion = ProximaCalibracionTXT.getText();
        String proovedoresDeServicios = ProvedorServicioTXT.getText();
        String encendidoDenoche = EncendidoNocheSi.isSelected() ? "SI" : "NO";
        String nombreProducto = NombreProductoTXT.getText();
        String inventarioExistente = InventarioExistenteTXT.getText();
        String observaciones = ObservacionesTXT.getText();
        
    }//GEN-LAST:event_CrearEquiposFinalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AplicacionTXT;
    private javax.swing.JPanel BackgroundCrearEquipos2;
    private javax.swing.JButton CrearEquiposFinal;
    private javax.swing.ButtonGroup EncendidoNoche;
    private javax.swing.JRadioButton EncendidoNocheNo;
    private javax.swing.JRadioButton EncendidoNocheSi;
    private javax.swing.JTextField InventarioExistenteTXT;
    private javax.swing.JComboBox<String> LabDisponible;
    private javax.swing.JTextField NombreProductoTXT;
    private javax.swing.JTextField ObservacionesTXT;
    private javax.swing.JTextField ProvedorServicioTXT;
    private javax.swing.JTextField ProximaCalibracionTXT;
    private javax.swing.JTextField ProximoMantenimientoTXT;
    private javax.swing.JTextField UltimaCalibracionTXT;
    private javax.swing.JTextField UltimoMantenimientoTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JLabel nameLbl10;
    private javax.swing.JLabel nameLbl11;
    private javax.swing.JLabel nameLbl12;
    private javax.swing.JLabel nameLbl3;
    private javax.swing.JLabel nameLbl4;
    private javax.swing.JLabel nameLbl5;
    private javax.swing.JLabel nameLbl6;
    private javax.swing.JLabel nameLbl7;
    private javax.swing.JLabel nameLbl8;
    private javax.swing.JLabel nameLbl9;
    // End of variables declaration//GEN-END:variables
}
