/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import controller.ListaDeEquipos;
import controller.ListaDeUsuarios;
import controller.ListaLaboratorios;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Laboratorio;
import model.Usuario;

/**
 *
 * @author derno
 */
public class CrearEquipos2 extends javax.swing.JPanel {
    
    private Usuario userActual;
    private ListaLaboratorios listalaboratorios;
    private ListaDeEquipos listaequipos;
    
    private String descripcion;
    private String marca;
    private String modelo;
    private String numeroSerial;
    private String numeroActivo;
    private String presentacion;
    private String voltaje;
    private String procesable;
    private String materialRequerido;
    private String añoDeCompra;
    
    public CrearEquipos2(Usuario user, ListaLaboratorios listaLab, ListaDeEquipos equipos, 
                     String descripcion, String marca, String modelo, String numeroSerial, 
                     String numeroActivo, String presentacion, String voltaje, 
                     String procesable, String materialRequerido, String añoDeCompra) {
    initComponents();
    this.userActual = user;
    this.listalaboratorios = listaLab;
    this.listaequipos = equipos;
    this.descripcion = descripcion;
    this.marca = marca;
    this.modelo = modelo;
    this.numeroSerial = numeroSerial;
    this.numeroActivo = numeroActivo;
    this.presentacion = presentacion;
    this.voltaje = voltaje;
    this.procesable = procesable;
    this.materialRequerido = materialRequerido;
    this.añoDeCompra =  añoDeCompra;
    initLabDisponible();
    
    LabDisponible.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            LabDisponibleActionPerformed(evt);
        }
    });
    }
    
      private void MostrarJpanel(JPanel p){
        p.setSize(1180,780);   
        p.setLocation(0,0);
        BackgroundCrearEquipos2.removeAll();
        BackgroundCrearEquipos2.add(p,BorderLayout.CENTER);
        BackgroundCrearEquipos2.revalidate();
        BackgroundCrearEquipos2.repaint();
    }
    private void initLabDisponible() {
        ArrayList<Laboratorio> laboratorios = listalaboratorios.getListaLaboratorios();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        for (Laboratorio lab : laboratorios) {
            model.addElement(lab.getNombreLaboratorio());
        }

        LabDisponible.setModel(model);
    }

    private void LabDisponibleActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String nombreLaboratorioSeleccionado = (String) LabDisponible.getSelectedItem();
        String idLaboratorio = listalaboratorios.listarLaboratorioPorNombre(nombreLaboratorioSeleccionado);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EncendidoNoche = new javax.swing.ButtonGroup();
        BackgroundCrearEquipos2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLbl1 = new javax.swing.JLabel();
        AplicacionTXT = new javax.swing.JTextField();
        CrearEquiposFinal = new javax.swing.JButton();
        nameLbl3 = new javax.swing.JLabel();
        UltimoMantenimientoTXT = new javax.swing.JTextField();
        nameLbl6 = new javax.swing.JLabel();
        ProximaCalibracionTXT = new javax.swing.JTextField();
        nameLbl4 = new javax.swing.JLabel();
        ProvedorServicioTXT = new javax.swing.JTextField();
        nameLbl5 = new javax.swing.JLabel();
        ProximoMantenimientoTXT = new javax.swing.JTextField();
        nameLbl7 = new javax.swing.JLabel();
        UltimaCalibracionTXT = new javax.swing.JTextField();
        nameLbl9 = new javax.swing.JLabel();
        NombreProductoTXT = new javax.swing.JTextField();
        nameLbl10 = new javax.swing.JLabel();
        ObservacionesTXT = new javax.swing.JTextField();
        nameLbl8 = new javax.swing.JLabel();
        EncendidoNocheSi = new javax.swing.JRadioButton();
        EncendidoNocheNo = new javax.swing.JRadioButton();
        nameLbl12 = new javax.swing.JLabel();
        InventarioExistenteTXT = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        nameLbl11 = new javax.swing.JLabel();
        LabDisponible = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(1038, 666));
        setPreferredSize(new java.awt.Dimension(1038, 666));

        BackgroundCrearEquipos2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Crear Equipo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Por favor, ingrese los datos para poder crear el equipo: ");

        nameLbl1.setText("Ingrese la aplicacion:");

        CrearEquiposFinal.setBackground(new java.awt.Color(21, 101, 192));
        CrearEquiposFinal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearEquiposFinal.setForeground(new java.awt.Color(255, 255, 255));
        CrearEquiposFinal.setText("Crear");
        CrearEquiposFinal.setBorder(null);
        CrearEquiposFinal.setBorderPainted(false);
        CrearEquiposFinal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearEquiposFinal.setIconTextGap(13);
        CrearEquiposFinal.setInheritsPopupMenu(true);
        CrearEquiposFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEquiposFinalActionPerformed(evt);
            }
        });

        nameLbl3.setText("Ingrese el ultimo mantenimiento:");

        nameLbl6.setText("Ingrese la proxima calibracion:");

        nameLbl4.setText("Ingrese el provedor de servicio:");

        nameLbl5.setText("Ingrese el proximo mantenimiento:");

        nameLbl7.setText("Ingrese la ultima calibracion:");

        nameLbl9.setText("Nombre del producto:");

        nameLbl10.setText("Ingrese las observaciones: ");

        nameLbl8.setText("Encendido de noche:");

        EncendidoNoche.add(EncendidoNocheSi);
        EncendidoNocheSi.setText("Si");

        EncendidoNoche.add(EncendidoNocheNo);
        EncendidoNocheNo.setText("No");

        nameLbl12.setText("Inventario existente:");

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));

        nameLbl11.setText("Escoja el laboratorio a asignar:");

        LabDisponible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout BackgroundCrearEquipos2Layout = new javax.swing.GroupLayout(BackgroundCrearEquipos2);
        BackgroundCrearEquipos2.setLayout(BackgroundCrearEquipos2Layout);
        BackgroundCrearEquipos2Layout.setHorizontalGroup(
            BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(189, 189, 189))
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                        .addComponent(nameLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(47, 47, 47))
                                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                        .addComponent(nameLbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(25, 25, 25))
                                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                        .addComponent(nameLbl7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(38, 38, 38))
                                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(UltimoMantenimientoTXT)
                                            .addComponent(AplicacionTXT)
                                            .addComponent(ProximoMantenimientoTXT)
                                            .addComponent(UltimaCalibracionTXT))
                                        .addGap(2, 2, 2))))
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(ProvedorServicioTXT)
                                .addGap(2, 2, 2))
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(42, 42, 42))
                            .addComponent(ProximaCalibracionTXT)
                            .addComponent(nameLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addComponent(LabDisponible, 0, 108, Short.MAX_VALUE)
                        .addGap(408, 408, 408))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CrearEquiposFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ObservacionesTXT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(187, 187, 187))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl8, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addGap(319, 319, 319))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(EncendidoNocheSi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(EncendidoNocheNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(333, 333, 333))
                            .addComponent(NombreProductoTXT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(243, 243, 243))
                            .addComponent(InventarioExistenteTXT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(316, 316, 316))
                            .addComponent(nameLbl11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49))))
        );
        BackgroundCrearEquipos2Layout.setVerticalGroup(
            BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AplicacionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UltimoMantenimientoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ProximoMantenimientoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(UltimaCalibracionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ProximaCalibracionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ProvedorServicioTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(nameLbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EncendidoNocheNo)
                            .addComponent(EncendidoNocheSi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLbl9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombreProductoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLbl12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InventarioExistenteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLbl10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ObservacionesTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLbl11)
                        .addGap(18, 18, 18)
                        .addComponent(LabDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CrearEquiposFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackgroundCrearEquipos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCrearEquipos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearEquiposFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEquiposFinalActionPerformed
        String aplicacion = AplicacionTXT.getText();
        String ultimoMantenimiento = UltimoMantenimientoTXT.getText();
        String proximoMantenimiento = ProximoMantenimientoTXT.getText();
        String ultimaCalibracion = UltimaCalibracionTXT.getText();
        String proximaCalibracion = ProximaCalibracionTXT.getText();
        String proovedoresDeServicios = ProvedorServicioTXT.getText();
        String encendidoDenoche = EncendidoNocheSi.isSelected() ? "SI" : "NO";
        String nombreProducto = NombreProductoTXT.getText();
        String inventarioExistente = InventarioExistenteTXT.getText();
        String observaciones = ObservacionesTXT.getText();
        
        String nombreLaboratorioSeleccionado = (String) LabDisponible.getSelectedItem();
        String idLaboratorio = listalaboratorios.listarLaboratorioPorNombre(nombreLaboratorioSeleccionado);

        boolean creado = listaequipos.crearProductoEquipo(userActual, descripcion, marca, modelo, numeroSerial, numeroActivo,
                presentacion, voltaje, procesable, materialRequerido, añoDeCompra, aplicacion, ultimoMantenimiento,
                proximoMantenimiento, ultimaCalibracion, proximaCalibracion, proovedoresDeServicios, encendidoDenoche,
                nombreProducto, inventarioExistente, observaciones, idLaboratorio);

        if (creado) {
            JOptionPane.showMessageDialog(this, "Equipo creado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
        } else {
            JOptionPane.showMessageDialog(this, "Error al crear el equipo. Verifique los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CrearEquiposFinalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AplicacionTXT;
    private javax.swing.JPanel BackgroundCrearEquipos2;
    private javax.swing.JButton CrearEquiposFinal;
    private javax.swing.ButtonGroup EncendidoNoche;
    private javax.swing.JRadioButton EncendidoNocheNo;
    private javax.swing.JRadioButton EncendidoNocheSi;
    private javax.swing.JTextField InventarioExistenteTXT;
    private javax.swing.JComboBox<String> LabDisponible;
    private javax.swing.JTextField NombreProductoTXT;
    private javax.swing.JTextField ObservacionesTXT;
    private javax.swing.JTextField ProvedorServicioTXT;
    private javax.swing.JTextField ProximaCalibracionTXT;
    private javax.swing.JTextField ProximoMantenimientoTXT;
    private javax.swing.JTextField UltimaCalibracionTXT;
    private javax.swing.JTextField UltimoMantenimientoTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JLabel nameLbl10;
    private javax.swing.JLabel nameLbl11;
    private javax.swing.JLabel nameLbl12;
    private javax.swing.JLabel nameLbl3;
    private javax.swing.JLabel nameLbl4;
    private javax.swing.JLabel nameLbl5;
    private javax.swing.JLabel nameLbl6;
    private javax.swing.JLabel nameLbl7;
    private javax.swing.JLabel nameLbl8;
    private javax.swing.JLabel nameLbl9;
    // End of variables declaration//GEN-END:variables
}
