/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import controller.ListaDeEquipos;
import controller.ListaDeUsuarios;
import controller.ListaLaboratorios;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import model.Usuario;

/**
 *
 * @author derno
 */
public class CrearEquipos2 extends javax.swing.JPanel {
    
    private Usuario userActual;
    private ListaLaboratorios listalaboratorios;
    private ListaDeEquipos listaequipos;
    
    public CrearEquipos2(Usuario user,ListaLaboratorios listaLab,ListaDeEquipos equipos ) {
        initComponents();
        this.userActual=user;
        this.listalaboratorios=listaLab;
        this.listaequipos=equipos;
    }
    
      private void MostrarJpanel(JPanel p){
        p.setSize(760,478);   
        p.setLocation(0,0);
        BackgroundCrearEquipos2.removeAll();
        BackgroundCrearEquipos2.add(p,BorderLayout.CENTER);
        BackgroundCrearEquipos2.revalidate();
        BackgroundCrearEquipos2.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EncendidoNoche = new javax.swing.ButtonGroup();
        BackgroundCrearEquipos2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLbl1 = new javax.swing.JLabel();
        AplicacionTXT = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        CrearEquipo = new javax.swing.JButton();
        nameLbl3 = new javax.swing.JLabel();
        UltimoMantenimientoTXT = new javax.swing.JTextField();
        nameLbl6 = new javax.swing.JLabel();
        CodigoTXT = new javax.swing.JTextField();
        nameLbl4 = new javax.swing.JLabel();
        NombreProductoTXT = new javax.swing.JTextField();
        nameLbl5 = new javax.swing.JLabel();
        UltimaCalibracionTXT = new javax.swing.JTextField();
        nameLbl7 = new javax.swing.JLabel();
        ProvedorServiciosTXT = new javax.swing.JTextField();
        nameLbl8 = new javax.swing.JLabel();
        nameLbl9 = new javax.swing.JLabel();
        ProcesableTXT = new javax.swing.JTextField();
        nameLbl10 = new javax.swing.JLabel();
        MaterialRequeridoTXT = new javax.swing.JTextField();
        EncendidoNocheSi = new javax.swing.JRadioButton();
        EncendidoNocheNo = new javax.swing.JRadioButton();

        BackgroundCrearEquipos2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Crear Equipo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Por favor, ingrese los datos para poder crear el equipo: ");

        nameLbl1.setText("Ingrese la aplicacion:");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        CrearEquipo.setBackground(new java.awt.Color(21, 101, 192));
        CrearEquipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearEquipo.setForeground(new java.awt.Color(255, 255, 255));
        CrearEquipo.setText("Crear");
        CrearEquipo.setBorder(null);
        CrearEquipo.setBorderPainted(false);
        CrearEquipo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CrearEquipo.setIconTextGap(13);
        CrearEquipo.setInheritsPopupMenu(true);
        CrearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEquipoActionPerformed(evt);
            }
        });

        nameLbl3.setText("Ingrese el ultimo mantenimiento:");

        nameLbl6.setText("Ingrese el codigo:");

        nameLbl4.setText("Ingrese el nombre del producto:");

        nameLbl5.setText("Ingrese la ultima calibracion:");

        nameLbl7.setText("Ingrese el provedor de servicios:");

        nameLbl8.setText("Encendido de noche:");

        nameLbl9.setText("Ingrese el inventario existente:");

        nameLbl10.setText("Ingrese las observaciones: ");

        EncendidoNoche.add(EncendidoNocheSi);
        EncendidoNocheSi.setText("Si");

        EncendidoNoche.add(EncendidoNocheNo);
        EncendidoNocheNo.setText("No");

        javax.swing.GroupLayout BackgroundCrearEquipos2Layout = new javax.swing.GroupLayout(BackgroundCrearEquipos2);
        BackgroundCrearEquipos2.setLayout(BackgroundCrearEquipos2Layout);
        BackgroundCrearEquipos2Layout.setHorizontalGroup(
            BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UltimoMantenimientoTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                                .addComponent(AplicacionTXT)
                                .addComponent(nameLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UltimaCalibracionTXT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProvedorServiciosTXT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLbl8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLbl5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLbl7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(EncendidoNocheSi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EncendidoNocheNo))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CodigoTXT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreProductoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProcesableTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialRequeridoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLbl10, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CrearEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(221, 221, 221))
        );
        BackgroundCrearEquipos2Layout.setVerticalGroup(
            BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl1)
                                .addGap(18, 18, 18)
                                .addComponent(AplicacionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLbl3)
                                .addGap(18, 18, 18)
                                .addComponent(UltimoMantenimientoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nameLbl5)
                                .addGap(18, 18, 18)
                                .addComponent(UltimaCalibracionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameLbl7)
                                .addGap(18, 18, 18)
                                .addComponent(ProvedorServiciosTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nameLbl8)
                                .addGap(18, 18, 18)
                                .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EncendidoNocheSi)
                                    .addComponent(EncendidoNocheNo)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundCrearEquipos2Layout.createSequentialGroup()
                                .addComponent(nameLbl4)
                                .addGap(18, 18, 18)
                                .addComponent(NombreProductoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameLbl9)
                                .addGap(18, 18, 18)
                                .addComponent(ProcesableTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nameLbl10)
                                .addGap(18, 18, 18)
                                .addComponent(MaterialRequeridoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameLbl6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundCrearEquipos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CrearEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BackgroundCrearEquipos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCrearEquipos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEquipoActionPerformed

    }//GEN-LAST:event_CrearEquipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AplicacionTXT;
    private javax.swing.JPanel BackgroundCrearEquipos2;
    private javax.swing.JTextField CodigoTXT;
    private javax.swing.JButton CrearEquipo;
    private javax.swing.ButtonGroup EncendidoNoche;
    private javax.swing.JRadioButton EncendidoNocheNo;
    private javax.swing.JRadioButton EncendidoNocheSi;
    private javax.swing.JTextField MaterialRequeridoTXT;
    private javax.swing.JTextField NombreProductoTXT;
    private javax.swing.JTextField ProcesableTXT;
    private javax.swing.JTextField ProvedorServiciosTXT;
    private javax.swing.JTextField UltimaCalibracionTXT;
    private javax.swing.JTextField UltimoMantenimientoTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JLabel nameLbl10;
    private javax.swing.JLabel nameLbl3;
    private javax.swing.JLabel nameLbl4;
    private javax.swing.JLabel nameLbl5;
    private javax.swing.JLabel nameLbl6;
    private javax.swing.JLabel nameLbl7;
    private javax.swing.JLabel nameLbl8;
    private javax.swing.JLabel nameLbl9;
    // End of variables declaration//GEN-END:variables
}
