package Views;

import controller.ListaDeEquipos;
import controller.ListaLaboratorios;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Equipo;
import model.Laboratorio;
import model.Usuario;

public class EquiposMantenimiento extends javax.swing.JPanel {

    private ListaLaboratorios listalaboratorios;
    private Usuario userActual;
    private ListaDeEquipos listaequipos;
    private DefaultTableModel tableModelEquipos;
    private HashMap<Integer, String> idMapEquipos;

    public EquiposMantenimiento(Usuario user, ListaLaboratorios listaLab, ListaDeEquipos equipos) {
        this.listalaboratorios = listaLab;
        this.listaequipos = equipos;
        this.userActual = user;
        idMapEquipos = new HashMap<>();
        initComponents();
        InitStyles();
        inicializarTablaEquipos(); 
        actualizarTablaEquipos();
        bloquearPorRol(userActual);
    }

    private void inicializarTablaEquipos() {
        String[] columnas = {"Nombre","Último Mantenimiento","Próximo Mantenimiento", "Laboratorio"};
        tableModelEquipos = new DefaultTableModel(columnas, 0);
        jTable1.setModel(tableModelEquipos);
    }
    
    private void bloquearPorRol(Usuario user){
        if(user.verificarRol(user,"Invitado")){
            BotonModificarEquipo.setEnabled(false);
        }
    }

    private void actualizarTablaEquipos() {
        tableModelEquipos.setRowCount(0);
        idMapEquipos.clear();
        int row = 0;

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        try {
            ArrayList<Equipo> equipos=null;
            if((userActual.getRolUsuario().equals("Tecnico"))||(userActual.getRolUsuario().equals("Invitado"))){
                equipos = null;
            }
            else if(userActual.getRolUsuario().equals("Administrador")){
                equipos = listaequipos.getListaEquiposMantenimiento();
            }
            if (equipos != null) {
                for (Equipo equipo : equipos) {
                    Laboratorio laboratorio = listalaboratorios.listarLaboratorio(equipo.getLaboratorio());
                    String nombreLaboratorio = (laboratorio != null) ? laboratorio.getNombreLaboratorio() : "Desconocido";

                    Object[] fila = {
                        equipo.getNombreProducto(),
                        equipo.getUltimoMantenimiento(),
                        equipo.getProximoMantenimiento(),
                        nombreLaboratorio
                    };
                    tableModelEquipos.addRow(fila);

                    idMapEquipos.put(row, equipo.getId());

                    for (int i = 0; i < tableModelEquipos.getColumnCount(); i++) {
                        jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
                    }

                    row++;
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Los Invitados y Tecnicos no pueden ver el modulo de mantenimiento", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener la lista de equipos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void InitStyles() {
        title.putClientProperty("FlatLaf.styleClass", "h1");
        title.setForeground(Color.black);
    }

    private void MostrarJPanel(JPanel p) {
        p.setSize(1392, 698);
        p.setLocation(0, 0);
        BackgroundEquipos.removeAll();
        BackgroundEquipos.add(p, BorderLayout.CENTER);
        BackgroundEquipos.revalidate();
        BackgroundEquipos.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundEquipos = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BotonModificarEquipo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        BackgroundEquipos.setBackground(new java.awt.Color(255, 255, 255));

        title.setText("Mantenimiento de equipos");

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BotonModificarEquipo.setBackground(new java.awt.Color(18, 90, 173));
        BotonModificarEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonModificarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        BotonModificarEquipo.setText("Editar");
        BotonModificarEquipo.setBorderPainted(false);
        BotonModificarEquipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonModificarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundEquiposLayout = new javax.swing.GroupLayout(BackgroundEquipos);
        BackgroundEquipos.setLayout(BackgroundEquiposLayout);
        BackgroundEquiposLayout.setHorizontalGroup(
            BackgroundEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundEquiposLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(699, 699, 699))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundEquiposLayout.createSequentialGroup()
                        .addGroup(BackgroundEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BackgroundEquiposLayout.createSequentialGroup()
                                .addGap(675, 675, 675)
                                .addComponent(BotonModificarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(39, 39, 39))))
        );
        BackgroundEquiposLayout.setVerticalGroup(
            BackgroundEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundEquiposLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(BotonModificarEquipo)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

    }//GEN-LAST:event_jTable1MousePressed

    private void BotonModificarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarEquipoActionPerformed
       int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
        String idEquipo = idMapEquipos.get(selectedRow);
        Equipo equipo = null;
        try {
            equipo = listaequipos.listarEquipo(idEquipo);
        } catch (ParseException ex) {
            Logger.getLogger(EquiposMantenimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (equipo != null) {
            MostrarJPanel(new ModificarEquipos(userActual, listalaboratorios, listaequipos, equipo));
        } else {
            JOptionPane.showMessageDialog(null, "Equipo no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila para modificar.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BotonModificarEquipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundEquipos;
    private javax.swing.JButton BotonModificarEquipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}