/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import controller.ListaDeUsuarios;
import controller.ListaLaboratorios;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Laboratorio;
import model.Usuario;

/**
 *
 * @author derno
 */
    public class ModificarLaboratorio extends javax.swing.JPanel {

        private ListaDeUsuarios listaUsuarios; 
        private ListaLaboratorios listalaboratorios; 
        private Usuario userActual;
        private DefaultTableModel tableModelAdmin;
        private DefaultTableModel tableModelAdminDisp;
        private Laboratorio laboratorioActual;

    public ModificarLaboratorio(Usuario user, ListaLaboratorios laboratorios, ListaDeUsuarios usuarios, Laboratorio laboratorio) {
            this.listaUsuarios = usuarios;
            this.listalaboratorios = laboratorios;
            this.userActual = user;
            this.laboratorioActual = laboratorio;
            initComponents();
            inicializarTablas();
            cargarDatosLaboratorio();
            cargarAdminAsignado();
            cargarAdminsDisponibles();
        }

    private void inicializarTablas() {
        String[] columnasAdmin = {"Administrador Asignado"};
        tableModelAdmin = new DefaultTableModel(columnasAdmin, 0);
        JTableAdmin.setModel(tableModelAdmin);

        String[] columnasAdminDisp = {"Administradores/Técnicos Disponibles"};
        tableModelAdminDisp = new DefaultTableModel(columnasAdminDisp, 0);
        JTableAdminDisp.setModel(tableModelAdminDisp);
    }
    
    private String[] facultadComboBox(String facultad){
        String[]escuela=new String[5];
        if(facultad.equals("Ciencias Economicas")){
            escuela[0]="Administracion de empresas";
            escuela[1]="Contaduria publica";
            escuela[2]="Relaciones Industriales";
            escuela[3]="Sociologia";
            escuela[4]="Economia";
        }
        if(facultad.equals("Humanidades y Educacion")){
            escuela[0]="Educacion";
            escuela[1]="Comunicacion Social";
            escuela[2]="Psicologia";
            escuela[3]="Letras";
            escuela[4]="Filosofia";
        }
        if(facultad.equals("Ingenieria")){
            escuela[0]="Ingenieria Civil";
            escuela[1]="Ingenieria Informatica";
            escuela[2]="Ingenieria Industrial";
            escuela[3]="Ingenieria Telecomunicaciones";
            escuela[4]="Arquitectura";
        }
        if(facultad.equals("Derecho")){
            escuela=new String[2];
            escuela[0]="Derecho";
            escuela[1]="Derecho ITER";
        }
        if(facultad.equals("Seleccionar")){
            escuela=new String[1];
            escuela[0]="Seleccionar facultad primero";
        }
        return escuela;
    }

    private void cargarDatosLaboratorio() {
        if (laboratorioActual != null) {
            NombreLaboratorioTxt.setText(laboratorioActual.getNombreLaboratorio());
            DepartamentoTxt.setText(laboratorioActual.getDepartamento());
            jComboBox1.setSelectedItem(laboratorioActual.getFacultad());
            jComboBox2.setSelectedItem(laboratorioActual.getEscuela());
        }
    }

    private void cargarAdminAsignado() {
    tableModelAdmin = new DefaultTableModel(new Object[]{"Administrador Asignado"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    JTableAdmin.setModel(tableModelAdmin);
    
    if (laboratorioActual != null) {
        Usuario admin = listaUsuarios.listarUsuario(laboratorioActual.getIdAdministrador());
        if (admin != null) {
            tableModelAdmin.addRow(new Object[]{admin.getNombreUser()});
        }
    }
}

    private void cargarAdminsDisponibles() {
    tableModelAdminDisp = new DefaultTableModel(new Object[]{"Administradores/Técnicos Disponibles"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    JTableAdminDisp.setModel(tableModelAdminDisp);

    for (Usuario usuario : listaUsuarios.getListaUsuarios()) {
        if (usuario.getRolUsuario().equals("Administrador") || usuario.getRolUsuario().equals("Tecnico")) {
            tableModelAdminDisp.addRow(new Object[]{usuario.getNombreUser()});
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rol = new javax.swing.ButtonGroup();
        Estado = new javax.swing.ButtonGroup();
        BackgroundCrearUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLbl1 = new javax.swing.JLabel();
        NombreLaboratorioTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ModificarLaboratorio = new javax.swing.JButton();
        nameLbl3 = new javax.swing.JLabel();
        nameLbl6 = new javax.swing.JLabel();
        nameLbl4 = new javax.swing.JLabel();
        DepartamentoTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableAdmin = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableAdminDisp = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        BackgroundCrearUsuario.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Modificar laboratorio");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Por favor, ingrese los datos para poder modificar el laboratorio: ");

        nameLbl1.setText("Nombre del laboratorio:");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        ModificarLaboratorio.setBackground(new java.awt.Color(21, 101, 192));
        ModificarLaboratorio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ModificarLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        ModificarLaboratorio.setText("Modificar");
        ModificarLaboratorio.setBorder(null);
        ModificarLaboratorio.setBorderPainted(false);
        ModificarLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ModificarLaboratorio.setIconTextGap(13);
        ModificarLaboratorio.setInheritsPopupMenu(true);
        ModificarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarLaboratorioActionPerformed(evt);
            }
        });

        nameLbl3.setText("Facultad:");

        nameLbl6.setText("Escuela:");

        nameLbl4.setText("Departamento:");

        JTableAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTableAdmin);

        JTableAdminDisp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(JTableAdminDisp);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Ciencias Economicas", "Humanidades y Educacion", "Ingenieria", "Derecho" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar facultad primero" }));

        javax.swing.GroupLayout BackgroundCrearUsuarioLayout = new javax.swing.GroupLayout(BackgroundCrearUsuario);
        BackgroundCrearUsuario.setLayout(BackgroundCrearUsuarioLayout);
        BackgroundCrearUsuarioLayout.setHorizontalGroup(
            BackgroundCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(BackgroundCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1004, 1004, 1004))
                    .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                        .addGroup(BackgroundCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                                .addComponent(nameLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(95, 95, 95))
                            .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                                .addGroup(BackgroundCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1)
                                        .addComponent(NombreLaboratorioTxt)
                                        .addComponent(jScrollPane2))
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                                .addGroup(BackgroundCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                                        .addComponent(nameLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(185, 185, 185))
                                    .addGroup(BackgroundCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ModificarLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DepartamentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(193, 193, 193))
                            .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        BackgroundCrearUsuarioLayout.setVerticalGroup(
            BackgroundCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(nameLbl6)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(nameLbl4)
                        .addGap(18, 18, 18)
                        .addComponent(DepartamentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(ModificarLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BackgroundCrearUsuarioLayout.createSequentialGroup()
                            .addComponent(nameLbl1)
                            .addGap(18, 18, 18)
                            .addComponent(NombreLaboratorioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(nameLbl3)
                            .addGap(27, 27, 27)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33))))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BackgroundCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarLaboratorioActionPerformed
        if ((!jComboBox1.getSelectedItem().equals("Seleccionar")) || (!jComboBox2.getSelectedItem().equals("Seleccionar facultad primero"))) {
            String nombreLaboratorio = NombreLaboratorioTxt.getText();
            String facultad=jComboBox1.getSelectedItem().toString();
            String escuela=jComboBox2.getSelectedItem().toString();
            String departamento = DepartamentoTxt.getText();

            int selectedRow = JTableAdminDisp.getSelectedRow();
            if (selectedRow != -1) {
                String nombreAdminSeleccionado = (String) tableModelAdminDisp.getValueAt(selectedRow, 0);
                String adminid = listaUsuarios.listarUsuarioPorNombre(nombreAdminSeleccionado);
                Usuario adminSeleccionado = listaUsuarios.listarUsuario(adminid);
                if (adminSeleccionado != null) {

                    boolean exito = listalaboratorios.modificarLaboratorio(userActual, laboratorioActual.getId(), nombreLaboratorio, facultad, escuela, departamento, adminid);

                    if (exito) {
                        JOptionPane.showMessageDialog(this, "Laboratorio modificado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al modificar el laboratorio.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Seleccione un administrador válido.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un administrador disponible.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Seleccione una opcion de facultad", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ModificarLaboratorioActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.jComboBox1.getSelectedIndex()>=0){
                this.jComboBox2.setModel(new DefaultComboBoxModel(this.facultadComboBox(this.jComboBox1.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundCrearUsuario;
    private javax.swing.JTextField DepartamentoTxt;
    private javax.swing.ButtonGroup Estado;
    private javax.swing.JTable JTableAdmin;
    private javax.swing.JTable JTableAdminDisp;
    private javax.swing.JButton ModificarLaboratorio;
    private javax.swing.JTextField NombreLaboratorioTxt;
    private javax.swing.ButtonGroup Rol;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JLabel nameLbl3;
    private javax.swing.JLabel nameLbl4;
    private javax.swing.JLabel nameLbl6;
    // End of variables declaration//GEN-END:variables
}
