/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import controller.ListaDeEquipos;
import controller.ListaDeInsumos;
import controller.ListaLaboratorios;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import model.Insumo;
import model.Usuario;

/**
 *
 * @author derno
 */
public class ModificarInsumos extends javax.swing.JPanel {
    
    private ListaLaboratorios listalaboratorios;
    private Usuario userActual;
    private ListaDeInsumos listaInsumos;
    private Insumo insumoActual;
    
    public ModificarInsumos(Usuario user, ListaLaboratorios listaLab, ListaDeInsumos insumos,Insumo insumo) {
        this.listalaboratorios = listaLab;
        this.listaInsumos = insumos;
        this.userActual = user;
        this.insumoActual = insumo;
        initComponents();
        cargarDatosInsumo();
    }
    public  void ShowJPanel(JPanel p) {
        p.setSize(1038, 666);
        p.setLocation(0,0);
        BackgroundCrearInsumo.removeAll();
        BackgroundCrearInsumo.add(p,BorderLayout.CENTER);
        BackgroundCrearInsumo.revalidate();
        BackgroundCrearInsumo.repaint();
    }
    private void cargarDatosInsumo() {
        if (insumoActual != null) {
            NombreInsumoTxt.setText(insumoActual.getNombreProducto());
            CategoriaInsumoTxt.setText(insumoActual.getCategoria());
            ClasificacionInsumoTxt.setText(insumoActual.getClasificacion());
            MarcaInsumoTxt.setText(insumoActual.getMarca());
            ModeloInsumoTxt.setText(insumoActual.getModelo());
            PresentacionInsumoTxt.setText(insumoActual.getPresentacion());
            DescripcioTxt.setText(insumoActual.getDescripcion());
            UnidadInsumoTxt.setText(insumoActual.getUnidad());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundCrearInsumo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLbl1 = new javax.swing.JLabel();
        NombreInsumoTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ModificarInsumoSiguiente = new javax.swing.JButton();
        nameLbl3 = new javax.swing.JLabel();
        MarcaInsumoTxt = new javax.swing.JTextField();
        nameLbl6 = new javax.swing.JLabel();
        ClasificacionInsumoTxt = new javax.swing.JTextField();
        nameLbl4 = new javax.swing.JLabel();
        ModeloInsumoTxt = new javax.swing.JTextField();
        nameLbl5 = new javax.swing.JLabel();
        CategoriaInsumoTxt = new javax.swing.JTextField();
        nameLbl7 = new javax.swing.JLabel();
        PresentacionInsumoTxt = new javax.swing.JTextField();
        nameLbl8 = new javax.swing.JLabel();
        UnidadInsumoTxt = new javax.swing.JTextField();
        nameLbl9 = new javax.swing.JLabel();
        DescripcioTxt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackgroundCrearInsumo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Crear Insumo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Por favor, ingrese los datos para poder crear el insumo: ");

        nameLbl1.setText("Nombre del insumo:");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        ModificarInsumoSiguiente.setBackground(new java.awt.Color(21, 101, 192));
        ModificarInsumoSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ModificarInsumoSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        ModificarInsumoSiguiente.setText("Siguente");
        ModificarInsumoSiguiente.setBorder(null);
        ModificarInsumoSiguiente.setBorderPainted(false);
        ModificarInsumoSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarInsumoSiguiente.setIconTextGap(13);
        ModificarInsumoSiguiente.setInheritsPopupMenu(true);
        ModificarInsumoSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarInsumoSiguienteActionPerformed(evt);
            }
        });

        nameLbl3.setText("Marca:");

        nameLbl6.setText("Clasificacion:");

        nameLbl4.setText("Modelo:");

        nameLbl5.setText("Categoria:");

        nameLbl7.setText("Presentacion:");

        nameLbl8.setText("Unidad:");

        nameLbl9.setText("Descripcion:");

        javax.swing.GroupLayout BackgroundCrearInsumoLayout = new javax.swing.GroupLayout(BackgroundCrearInsumo);
        BackgroundCrearInsumo.setLayout(BackgroundCrearInsumoLayout);
        BackgroundCrearInsumoLayout.setHorizontalGroup(
            BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1004, 1004, 1004))
                    .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(702, 702, 702))
                    .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                        .addGroup(BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                                .addGroup(BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameLbl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameLbl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(97, 97, 97))
                            .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                                .addGroup(BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreInsumoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                                    .addComponent(MarcaInsumoTxt)
                                    .addComponent(ModeloInsumoTxt)
                                    .addComponent(CategoriaInsumoTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                                .addComponent(nameLbl6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(611, 611, 611))
                            .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                                .addGroup(BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClasificacionInsumoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ModificarInsumoSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(PresentacionInsumoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nameLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(UnidadInsumoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nameLbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(DescripcioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nameLbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        BackgroundCrearInsumoLayout.setVerticalGroup(
            BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                        .addComponent(nameLbl1)
                        .addGap(18, 18, 18)
                        .addComponent(NombreInsumoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(nameLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MarcaInsumoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModeloInsumoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CategoriaInsumoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundCrearInsumoLayout.createSequentialGroup()
                        .addGroup(BackgroundCrearInsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BackgroundCrearInsumoLayout.createSequentialGroup()
                                .addComponent(nameLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ClasificacionInsumoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PresentacionInsumoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameLbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UnidadInsumoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameLbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DescripcioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(ModificarInsumoSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(118, 118, 118))))
        );

        add(BackgroundCrearInsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1082, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarInsumoSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarInsumoSiguienteActionPerformed
        String nombre = NombreInsumoTxt.getText();
        String categoria = CategoriaInsumoTxt.getText();
        String clasificacion = ClasificacionInsumoTxt.getText();
        String marca = MarcaInsumoTxt.getText();
        String modelo = ModeloInsumoTxt.getText();
        String presentacion = PresentacionInsumoTxt.getText();
        String descripcion = DescripcioTxt.getText();
        String unidad = UnidadInsumoTxt.getText();
        
        ShowJPanel(new ModificarInsumos2(userActual, listalaboratorios, listaInsumos, insumoActual, nombre, categoria, clasificacion, marca, modelo, presentacion, descripcion, unidad));
    }//GEN-LAST:event_ModificarInsumoSiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundCrearInsumo;
    private javax.swing.JTextField CategoriaInsumoTxt;
    private javax.swing.JTextField ClasificacionInsumoTxt;
    private javax.swing.JTextField DescripcioTxt;
    private javax.swing.JTextField MarcaInsumoTxt;
    private javax.swing.JTextField ModeloInsumoTxt;
    private javax.swing.JButton ModificarInsumoSiguiente;
    private javax.swing.JTextField NombreInsumoTxt;
    private javax.swing.JTextField PresentacionInsumoTxt;
    private javax.swing.JTextField UnidadInsumoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JLabel nameLbl3;
    private javax.swing.JLabel nameLbl4;
    private javax.swing.JLabel nameLbl5;
    private javax.swing.JLabel nameLbl6;
    private javax.swing.JLabel nameLbl7;
    private javax.swing.JLabel nameLbl8;
    private javax.swing.JLabel nameLbl9;
    // End of variables declaration//GEN-END:variables
}
