/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author derno
 */
public class Productos extends javax.swing.JPanel {
    
      private void MostrarJpanel(JPanel p){
        p.setSize(760,478);   
        p.setLocation(0,0);
        BackgroundTelevisor.removeAll();
        BackgroundTelevisor.add(p,BorderLayout.CENTER);
        BackgroundTelevisor.revalidate();
        BackgroundTelevisor.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundTelevisor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BotonEquipos = new javax.swing.JButton();
        BotonSustancias = new javax.swing.JButton();
        BotonInsumos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        BackgroundTelevisor.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundTelevisor.setPreferredSize(new java.awt.Dimension(1082, 630));

        jPanel2.setBackground(new java.awt.Color(21, 101, 192));

        BotonEquipos.setBackground(new java.awt.Color(21, 101, 192));
        BotonEquipos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonEquipos.setForeground(new java.awt.Color(255, 255, 255));
        BotonEquipos.setText("Equipos");
        BotonEquipos.setBorder(null);
        BotonEquipos.setBorderPainted(false);
        BotonEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonEquipos.setIconTextGap(13);
        BotonEquipos.setInheritsPopupMenu(true);
        BotonEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEquiposActionPerformed(evt);
            }
        });

        BotonSustancias.setBackground(new java.awt.Color(21, 101, 192));
        BotonSustancias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonSustancias.setForeground(new java.awt.Color(255, 255, 255));
        BotonSustancias.setText("Sustancias Quimicas");
        BotonSustancias.setBorder(null);
        BotonSustancias.setBorderPainted(false);
        BotonSustancias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonSustancias.setIconTextGap(13);
        BotonSustancias.setInheritsPopupMenu(true);
        BotonSustancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSustanciasActionPerformed(evt);
            }
        });

        BotonInsumos.setBackground(new java.awt.Color(21, 101, 192));
        BotonInsumos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonInsumos.setForeground(new java.awt.Color(255, 255, 255));
        BotonInsumos.setText("Insumos");
        BotonInsumos.setBorder(null);
        BotonInsumos.setBorderPainted(false);
        BotonInsumos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonInsumos.setIconTextGap(13);
        BotonInsumos.setInheritsPopupMenu(true);
        BotonInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInsumosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonSustancias, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(BotonInsumos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonSustancias, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundTelevisorLayout = new javax.swing.GroupLayout(BackgroundTelevisor);
        BackgroundTelevisor.setLayout(BackgroundTelevisorLayout);
        BackgroundTelevisorLayout.setHorizontalGroup(
            BackgroundTelevisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundTelevisorLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(351, 351, 351)
                .addComponent(jLabel1)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        BackgroundTelevisorLayout.setVerticalGroup(
            BackgroundTelevisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundTelevisorLayout.createSequentialGroup()
                .addGroup(BackgroundTelevisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundTelevisorLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundTelevisorLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEquiposActionPerformed
        MostrarJpanel(new Equipos());
    }//GEN-LAST:event_BotonEquiposActionPerformed

    private void BotonSustanciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSustanciasActionPerformed
        MostrarJpanel(new SustanciasQuimicas());
    }//GEN-LAST:event_BotonSustanciasActionPerformed

    private void BotonInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInsumosActionPerformed
        MostrarJpanel(new Insumos());
    }//GEN-LAST:event_BotonInsumosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundTelevisor;
    private javax.swing.JButton BotonEquipos;
    private javax.swing.JButton BotonInsumos;
    private javax.swing.JButton BotonSustancias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
